#!/bin/bash

#$ -cwd
#$ -j y
#$ -S /bin/bash
#$ -N dwiTestProc
#$ -m e
#$ -M arunh.garimella@gmail.com

#Keep for adding modules
. /etc/profile.d/modules.sh

module load gcc/8.3.0
module load mrtrix3/3.0_RC3
#module load fsl/5.0.11
#module load ants/2.3.1

DATA_DIR=/mnt/MD1200B/egarza/arun/Datasets/AddimexConn/dwi
SCRIPT_DIR=/mnt/MD1200B/egarza/arun/Datasets/AddimexConn/Scripts/DWI_Processing

for subId in $DATA_DIR/sub-149;
do
	id="$(basename ${subId})"
	${SCRIPT_DIR}/siftGen_2.sh ${id}
done
